### ISSUE TITLE
Uuringutegevuste nimekirja taustapilt

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#76]
Halduril on võimalik määrata uuringutegevuste nimekirja lehele taustapilt (870px x 145px):

![screen shot 2016-01-25 at 14 16 02](https://cloud.githubusercontent.com/assets/380007/12550738/54daaf58-c36e-11e5-9c0b-495757e3b997.png)

**Comment by mbrikker** [comment]
Kollases tekstis on kirjas lause "analoogselt teistel lehtedel, aga...", kas seda on ka teiste lehtede puhul arendatud või ainult sellel lehel?

**Comment by tammets** [comment]
Hetkel sellel lehel, palun täpsusta, millistel analoogsetel lehtedel?

**Comment by mbrikker** [comment]
Gruppide leht tegelikult ongi vist ainukene analoogse ehitusega. Analoogsete lehtede all sai mõeldud neid, millel on samamoodi pealkirja all mõni tab.

**Comment by pjotrsavitski** [comment]
Does this mean that Admin can upload an image that would be used as a background for the topmost part of the page?
Does it have to happen from the page itself or from some management page?
Will the uploaded page be with correct dimensions or should it be processed (the correct dimensions variant should be the best one as it would render the expected results).

Maybe live upload and replacement is not really needed and Administrator could just replace the preset image somewhere within the system? This does not seem like something to happen quite often. There is only one page for that, so it could become part of the UI design (so to say) instead of providing a highly dynamic uploading and replacing solution.

It could be dealt with as soon as it is decided.

**Comment by tammets** [comment]
Does this mean that Admin can upload an image that would be used as a background for the topmost part of the page? - **Yes**
Does it have to happen from the page itself or from some management page? - **Management page, if possible**
Will the uploaded page be with correct dimensions or should it be processed (the correct dimensions variant should be the best one as it would render the expected results). - **Do you mean uploaded image? If yes, then it should be already with correct dimensions before uploading process**
Maybe live upload and replacement is not really needed and Administrator could just replace the preset image somewhere within the system? - **It's not going to happen often but it should be possible to change the background without coding**

**Comment by pjotrsavitski** [comment]
The logic of how it would work has been decided. The upload will be possible from the backend (WP) side. The data loading for that case would have to be done with a standalone specialised call.

There should probably be some default image that is used until something else has been uploaded.

**Comment by mbrikker** [comment]
Vastav taustapilt, nimega "listing.jpg, asub järgmisel aadressil: https://drive.google.com/folderview?id=0B1cCT4KQ-CA8ZHZUNUhzZmtILU0&usp=sharing
