### ISSUE TITLE
Hall of Fame

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/Uuringulaegas#77]
Hall of Fame page displays 5 sections of student who have gained one or more badge from the list:
- Gold medal
- Silver medal
- Bronze medal
- Inquiry star
- Diploma

![screen shot 2016-02-16 at 13 53 27](https://cloud.githubusercontent.com/assets/380007/13075585/0602f568-d4b5-11e5-80bf-2f530ee20aff.png)

**Comment by mbrikker** [comment]
Tekstid Hall of Fame lehele, esimene tekstilõik kõige ette, ülejäänud vastavate pealkirjade alla. Kohas, kus on mainitud OpenBadges võimalust, võiks olla lause selle kohta kuidas OpenBadge' platvormis siduda oma Mozilla packbackiga:

**Hall of Fame**

In the Ark of Inquiry Project, an award system is designed to challenge and stimulate pupils to become responsible researchers and innovators. On this Hall of fame page we celebrate the success of our learners and make their accomplishments visible for all.

The award system consists of five awards: a star, diploma, bronze medal, silver medal, and a gold medal. The awards can be obtained cumulatively by individual learners. That means that in order to earn a gold medal, a pupil must obtain all other awards first. The awards a pupil obtained are published on the profile page and on this Hall of Fame page.

At stage 1 an inquiry star and diploma celebrate the ability to individually reflect on the relevance, consequences and ethics of processes and outcomes of inquiry for oneself, others and society. At stage 2 bronze, silver and gold medals celebrate excellent communication and discussion about the relevance, consequences and ethics of inquiry processes and outcomes for oneself, others and society with an audience.

Pupils can obtain up to all five awards during the time they participate in the Ark of Inquiry.

Together with their teachers pupils take active roles in getting nominated. Granting is organized by a national jury consisting of teachers, teacher educators and experts. The process of awarding is coordinated by a national administrator.

In addition to the awards, the Ark of Inquiry platform also features a set of OpenBadges. Badges can be obtained for completing a set of activities, for mastering a specific domain or just by showing initiative. Start collecting badges by starting your next inquiry activity!

Below are the learners who have been awarded inquiry awards by the Ark of Inquiry jury:

**Gold medalists**

Only 1% of all the learners will obtain a gold medal. In order to get a gold medal, learners will first have to obtain all other four awards. This award focusses on the attitude and ability to communicate and discuss processes and outcomes of inquiry with an audience. So let us celebrate our best inquirers and responsible researchers among us! Congratulations, dear gold medalists!

**Silver medalists**

Only 5% of all the learners will obtain a silver medal. In order to get a silver medal, learners will first have to obtain all other three awards. This award focusses on the attitude and ability to communicate and discuss processes and outcomes of inquiry with an audience. Congratulations, dear silver medalists!

**Bronze medalists**

Only 10% of all the learners will obtain a bronze medal. In order to get a bronze medal, learners will first have to obtain all other three awards. This award focusses on the attitude and ability to communicate and discuss processes and outcomes of inquiry with an audience. Congratulations, dear bronze medalists!

**Distinguished young scholars (*pealkirja võiks nii ära muuta, et young läheks vahele)**

Diplomas focus on the development of the attitude and ability to individually reflect on inquiry activities. Diplomas are granted for endeavours that pupils undertake to individually think through the relevance, consequences and ethics of processes and outcomes of the inquiry activity for themselves, others and/or society in a reflective report. Congratulations, our distinguished scholars!

**Renowned young scientists (*pealkirja võiks nii ära muuta, et young läheks vahele)**

Inquiry stars focus on the development of the attitude and ability to individually reflect on inquiry activities. Inquiry stars are granted for endeavours that pupils undertake to individually think through the relevance, consequences and ethics of processes and outcomes of the inquiry activity for themselves, others and/or society in a reflective report. Congratulations, our renowned scientists!
